name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install Qt
      run: brew install qt
          brew install qt@5
    - name: buildmac
      run: buildmac.sh
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
