name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: 'desktop'
        install-deps: 'true'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        set-env: 'true'
    - name: install qt tools
      run: sudu /Users/runner/hostedtoolcache/Python/3.11.3/x64/bin/python3 -m aqt install-tool mac desktop tools_ifw tools_qtcreator qt.tools.qtcreator tools_cmake --outputdir /Users/runner/work/subtivals/Qt
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
